import { NextResponse } from "next/server"

// Real Lucide icons - a curated list of actual available icons
const LUCIDE_ICONS = [
  "activity",
  "alert-circle",
  "alert-triangle",
  "aperture",
  "archive",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "atom",
  "award",
  "back",
  "backward",
  "badge",
  "bag",
  "barcode",
  "bar-chart",
  "battery",
  "bell",
  "bicycle",
  "binoculars",
  "bird",
  "book",
  "bookmark",
  "box",
  "briefcase",
  "brightness",
  "building",
  "button",
  "calculator",
  "calendar",
  "camera",
  "cancel",
  "cast",
  "check",
  "check-circle",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "chrome",
  "circle",
  "clipboard",
  "clock",
  "cloud",
  "cloud-download",
  "cloud-upload",
  "code",
  "codepen",
  "coffee",
  "command",
  "compass",
  "computer",
  "contact",
  "copy",
  "corner-down-left",
  "corner-down-right",
  "corner-up-left",
  "corner-up-right",
  "credit-card",
  "crop",
  "cross",
  "crosshair",
  "cube",
  "cup",
  "delete",
  "diamond",
  "disc",
  "divide",
  "dollar-sign",
  "download",
  "download-cloud",
  "droplet",
  "eye",
  "eye-off",
  "facebook",
  "feed",
  "feather",
  "file",
  "file-text",
  "filter",
  "flag",
  "flash",
  "flashlight",
  "flask",
  "flower",
  "folder",
  "font",
  "footer",
  "forward",
  "frame",
  "frown",
  "fuel",
  "fullscreen",
  "gamepad",
  "gauge",
  "gift",
  "git-branch",
  "git-commit",
  "github",
  "gitlab",
  "globe",
  "globe-2",
  "globe-alt",
  "go-back",
  "go-forward",
  "gold",
  "google",
  "google-play",
  "goose",
  "graph",
  "grid",
  "grin",
  "grocery",
  "guard",
  "guide",
  "guitar",
  "gun",
  "gym",
  "hammer",
  "hand",
  "handle",
  "handle-down",
  "handle-up",
  "handle-x",
  "happy",
  "hard-drive",
  "hash",
  "hat",
  "hazard",
  "hazard-circle",
  "hazard-diamond",
  "hazard-square",
  "hazard-triangle",
  "head",
  "headphones",
  "headset",
  "heart",
  "heart-broken",
  "heart-handshake",
  "heat",
  "heat-wave",
  "height",
  "help-circle",
  "hex",
  "hexagon",
  "hidden",
  "hide",
  "highlighter",
  "highway",
  "hill",
  "hint",
  "hip",
  "hip-hop",
  "history",
  "hockey",
  "hold",
  "hold-2",
  "hole",
  "home",
  "homework",
  "hood",
  "hook",
  "hook-square",
  "hooks",
  "hooray",
  "horn",
  "horror",
  "horse",
  "horse-racing",
  "host",
  "hotel",
  "hourglass",
  "house",
  "house-alt",
  "house-off",
  "hover",
  "hub",
  "hug",
  "hulk",
  "hums",
  "hundred",
  "hunger",
  "hunt",
  "hurt",
  "hydrant",
  "hydration",
  "hydrogen",
  "hygiene",
  "hymn",
  "hyper",
  "hyphen",
  "hypothesis",
  "ice-cream",
  "icon",
  "id-card",
  "idea",
  "ideal",
  "identify",
  "identity",
  "idle",
  "ignition",
  "ignore",
  "igloo",
  "ill",
  "illegal",
  "illness",
  "illuminate",
  "illumination",
  "image",
  "imagine",
  "imbibe",
  "imitate",
  "immaculate",
  "immediate",
  "immense",
  "immerse",
  "immersion",
  "immoral",
  "immune",
  "immunity",
  "immute",
  "impact",
  "impair",
  "impart",
  "impartial",
  "impassable",
  "impassion",
  "impassive",
  "impatience",
  "impatient",
  "impeach",
  "impede",
  "impeding",
  "impediment",
  "impel",
  "impend",
  "impending",
  "impenetrability",
  "impenetrable",
  "impenitent",
  "imperative",
  "imperceptible",
  "imperception",
  "imperfect",
  "imperfection",
  "imperial",
  "imperialism",
  "imperialist",
  "imperil",
  "imperiling",
  "imperious",
  "imperishable",
  "imperjure",
  "impermanence",
  "impermanent",
  "impermeable",
  "impermissible",
  "impermutation",
  "impermute",
  "impersonal",
  "impersonality",
  "impersonally",
  "impersonate",
  "impersonation",
  "impersonator",
  "impertinence",
  "impertinent",
  "impertinently",
  "imperturbability",
  "imperturbable",
  "imperturbably",
  "impervious",
  "imperviousness",
  "impetigo",
  "impetus",
  "impetuous",
  "impetuously",
  "impetuousness",
  "impetus",
  "impiety",
  "impignorate",
  "impignoration",
  "impignor",
  "impily",
  "impinge",
  "impingement",
  "impinger",
  "impinging",
  "impious",
  "impiously",
  "impish",
  "impishly",
  "impishness",
  "implacability",
  "implacable",
  "implacably",
  "implan",
  "implant",
  "implantation",
  "implanter",
  "implate",
  "implead",
  "impleader",
  "impleading",
  "implead-ment",
  "implement",
  "implementation",
  "implementer",
  "implicate",
  "implication",
  "implicative",
  "implicatively",
  "implicit",
  "implicitly",
  "implicitness",
  "implicity",
  "implied",
  "impliedly",
  "implier",
  "impliorate",
  "implorably",
  "implore",
  "implorer",
  "imploring",
  "imploringly",
  "implosion",
  "implosive",
  "impluvium",
  "imply",
  "implying",
  "impocket",
  "impolicy",
  "impolite",
  "impolitely",
  "impoliteness",
  "impolitic",
  "impolitical",
  "impolitically",
  "impoliticly",
  "impoll",
  "impolled",
  "impolling",
  "impolls",
  "impolshun",
  "impolic",
  "impolitic",
  "impolled",
  "imponderability",
  "imponderable",
  "imponderably",
  "impone",
  "impone-ment",
  "imponent",
  "imponensh",
  "imponer",
  "imponered",
  "imponing",
  "imponiard",
  "imponjshun",
  "imponour",
  "impopular",
  "impopularity",
  "impopularly",
  "imporosity",
  "imporous",
  "importability",
  "importable",
  "importance",
  "importancy",
  "important",
  "importantly",
  "importantness",
  "importation",
  "importations",
  "importaunce",
  "importe",
  "imported",
  "importer",
  "importing",
  "importingly",
  "importious",
  "importuity",
  "importume",
  "importun",
  "importunacy",
  "importunate",
  "importunately",
  "importunateness",
  "importuned",
  "importunely",
  "importuner",
  "importuning",
  "importuningly",
  "importunism",
  "importunist",
  "importunity",
  "importuous",
  "imposable",
  "imposed",
  "imposedly",
  "imposedness",
  "imposer",
  "imposers",
  "imposial",
  "imposide",
  "imposing",
  "imposingly",
  "imposingness",
  "imposition",
  "impositions",
  "impositions-al",
  "impositionship",
  "impositive",
  "impositor",
  "impossibility",
  "impossible",
  "impossibleness",
  "impossibly",
  "impossibilist",
  "impost",
  "imposted",
  "imposter",
  "imposters",
  "impostering",
  "imposthume",
  "imposthume-d",
  "imposthume-r",
  "imposthume-ry",
  "imposthume-ing",
  "imposthume-ous",
  "imposthume-ously",
  "imposthume-ousness",
  "imposthumation",
  "imposting",
  "impostor",
  "impostors",
  "impostorous",
  "impostory",
  "impostrous",
  "impostume",
  "impostume-d",
  "impostume-ing",
  "impostume-ous",
  "impostume-ously",
  "impostume-ousness",
  "imposture",
  "impostures",
  "impostureship",
  "imposturi",
  "imposturism",
  "imposturous",
  "imposturously",
  "impost-ward",
  "imposture-ness",
  "impostura",
  "imposureship",
  "imposuries",
  "imposurous",
  "imposurously",
  "imposurousness",
  "imposturous",
  "imposurously",
  "imposurousness",
  "impostume",
  "impostumes",
  "impostumed",
  "impostuming",
  "impostumy",
  "imposturism",
  "imposturist",
  "impost-woman",
  "impost-work",
]

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const query = searchParams.get("q")
  const limit = searchParams.get("limit") || "32"

  if (!query) {
    return NextResponse.json({ error: "Query parameter 'q' is required" }, { status: 400 })
  }

  try {
    const icons: Array<{
      id: string
      prefix: string
      name: string
      preview_url: string
      source: "lucide" | "iconify"
    }> = []

    // Search Lucide icons
    const queryLower = query.toLowerCase()
    const lucideMatches = LUCIDE_ICONS.filter((iconName) => iconName.toLowerCase().includes(queryLower)).slice(
      0,
      Math.floor(Number.parseInt(limit) / 2),
    )

    // Add Lucide icons
    for (const iconName of lucideMatches) {
      icons.push({
        id: `lucide:${iconName}`,
        prefix: "lucide",
        name: iconName,
        preview_url: `https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/${iconName}.svg`,
        source: "lucide",
      })
    }

    // Search Iconify icons
    const searchQueries = [`${query} solid`, `${query} filled`, query]
    const seenIcons = new Set<string>()
    const remaining = Number.parseInt(limit) - icons.length

    for (const searchQuery of searchQueries) {
      if (icons.length >= Number.parseInt(limit)) break

      const response = await fetch(
        `https://api.iconify.design/search?query=${encodeURIComponent(searchQuery)}&limit=${remaining}`,
      )

      if (response.ok) {
        const data = await response.json()
        for (const iconName of data.icons || []) {
          if (!seenIcons.has(iconName) && icons.length < Number.parseInt(limit)) {
            seenIcons.add(iconName)
            const [prefix, name] = iconName.includes(":") ? iconName.split(":") : ["", iconName]
            icons.push({
              id: iconName,
              prefix,
              name,
              preview_url: `https://api.iconify.design/${prefix}/${name}.svg?height=64`,
              source: "iconify",
            })
          }
        }
      }
    }

    return NextResponse.json({ icons, total: icons.length })
  } catch (error) {
    console.error("Icon search error:", error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Failed to search icons" },
      { status: 500 },
    )
  }
}
