// Shared resources constants - used by both main app and admin panel

export const CUSTOM_COLORS = [
  { id: "white", name: "White", color: "#ffffff" },
  { id: "black", name: "Black", color: "#1a1a1a" },
  { id: "red", name: "Red", color: "#e63946" },
  { id: "orange", name: "Orange", color: "#f77f00" },
  { id: "yellow", name: "Yellow", color: "#fcbf49" },
  { id: "green", name: "Green", color: "#2a9d8f" },
  { id: "blue", name: "Blue", color: "#457b9d" },
  { id: "purple", name: "Purple", color: "#7b2cbf" },
]

export const CUSTOM_TEXTURES = {
  normal: [
    { id: "normal-1", name: "Paint", url: "/images/custom/normal-1.jpg" },
    { id: "normal-2", name: "Smooth", url: "/images/custom/normal-2.jpg" },
    { id: "normal-3", name: "Drops", url: "/images/custom/normal-3.jpg" },
    { id: "normal-4", name: "Brushed", url: "/images/custom/normal-4.jpg" },
    { id: "normal-5", name: "Grid", url: "/images/custom/normal-5.jpg" },
    { id: "normal-6", name: "Crystals", url: "/images/custom/normal-6.jpg" },
    { id: "normal-7", name: "Waves", url: "/images/custom/normal-7.jpg" },
  ],
  roughness: [
    { id: "rough-1", name: "Smudges", url: "/images/custom/roughness-1.jpg" },
    { id: "rough-2", name: "Scratches", url: "/images/custom/roughness-2.jpg" },
    { id: "rough-3", name: "Matte", url: "/images/custom/roughness-3.jpg" },
    { id: "rough-4", name: "Glossy", url: "/images/custom/roughness-4.jpg" },
  ],
  metalness: [
    { id: "metal-1", name: "Fingerprints", url: "/images/custom/metalness-1.jpg" },
    { id: "metal-2", name: "Scratches", url: "/images/custom/metalness-2.jpg" },
    { id: "metal-3", name: "Dust", url: "/images/custom/metalness-3.jpg" },
    { id: "metal-4", name: "Clean", url: "/images/custom/metalness-4.jpg" },
  ],
}

export const MATERIAL_PRESETS = {
  plastic: {
    id: "plastic",
    name: "Scratched Plastic",
    type: "pbr" as const,
    baseColor: "/images/plastic017b-1k-jpg-color.jpg",
    normalMap: "/images/plastic017b-1k-jpg-normalgl.jpg",
    roughnessMap: "/images/plastic017b-1k-jpg-roughness.jpg",
    metalness: 0,
    roughness: 1,
    defaultTint: "#00ff88",
  },
  paint: {
    id: "paint",
    name: "Chipped Paint",
    type: "pbr" as const,
    baseColor: "/images/paint001-1k-jpg-color.jpg",
    normalMap: "/images/paint001-1k-jpg-normalgl.jpg",
    roughnessMap: "/images/paint001-1k-jpg-roughness.jpg",
    metalness: 0,
    roughness: 0.8,
    defaultTint: "#ff5722",
  },
  sponge: {
    id: "sponge",
    name: "Sponge",
    type: "pbr" as const,
    baseColor: "/images/sponge003-1k-jpg-color.jpg",
    normalMap: "/images/sponge003-1k-jpg-normalgl.jpg",
    roughnessMap: "/images/sponge003-1k-jpg-roughness.jpg",
    metalness: 0,
    roughness: 0.9,
    defaultTint: "#7ac943",
  },
  tactilePaving: {
    id: "tactilePaving",
    name: "Tactile Paving",
    type: "pbr" as const,
    baseColor: "/images/tactilepaving003-1k-jpg-color.jpg",
    normalMap: "/images/tactilepaving003-1k-jpg-normalgl.jpg",
    roughnessMap: "/images/tactilepaving003-1k-jpg-roughness.jpg",
    metalness: 0,
    roughness: 0.7,
    defaultTint: "#f4d03f",
  },
  terrazzo: {
    id: "terrazzo",
    name: "Terrazzo",
    type: "pbr" as const,
    baseColor: "/images/terrazzo-color.jpg",
    normalMap: "/images/terrazzo-normal.jpg",
    roughnessMap: "/images/terrazzo-roughness.jpg",
    metalness: 0.1,
    roughness: 0.7,
    defaultTint: "#ffffff",
  },
  paintedMetal: {
    id: "paintedMetal",
    name: "Painted Metal",
    type: "pbr" as const,
    baseColor: "/images/painted-metal-color.jpg",
    normalMap: "/images/painted-metal-normal.jpg",
    roughnessMap: "/images/painted-metal-roughness.jpg",
    metalness: 0.3,
    roughness: 0.8,
    defaultTint: "#ffffff",
  },
  glazedTerracotta: {
    id: "glazedTerracotta",
    name: "Glazed Terracotta",
    type: "pbr" as const,
    baseColor: "/images/glazed-terracotta-color.jpg",
    normalMap: "/images/glazed-terracotta-normal.jpg",
    roughnessMap: "/images/glazed-terracotta-roughness.jpg",
    metalness: 0.1,
    roughness: 0.6,
    defaultTint: "#ffffff",
  },
  goldenMetal: {
    id: "goldenMetal",
    name: "Golden Metal",
    type: "pbr" as const,
    baseColor: "/images/golden-metal-color.jpg",
    normalMap: "/images/golden-metal-normal.jpg",
    roughnessMap: "/images/golden-metal-roughness.jpg",
    metalness: 1.0,
    roughness: 0.3,
    defaultTint: "#ffffff",
  },
  silverSteel: {
    id: "silverSteel",
    name: "Silver Steel",
    type: "pbr" as const,
    baseColor: "/images/silver-steel-color.jpg",
    normalMap: "/images/silver-steel-normal.jpg",
    roughnessMap: "/images/silver-steel-roughness.jpg",
    metalness: 1.0,
    roughness: 0.25,
    defaultTint: "#ffffff",
  },
  dirtyGlass: {
    id: "dirtyGlass",
    name: "Dirty Glass",
    type: "pbr" as const,
    baseColor: null,
    normalMap: "/images/dirty-glass-normal.jpg",
    roughnessMap: "/images/dirty-glass-roughness.jpg",
    metalness: 0,
    roughness: 0.1,
    transmission: 0.98,
    ior: 1.52,
    defaultTint: "#ffffff",
  },
  scratchedGlass: {
    id: "scratchedGlass",
    name: "Scratched Glass",
    type: "pbr" as const,
    baseColor: null,
    normalMap: "/images/scratched-glass-normal.jpg",
    roughnessMap: "/images/scratched-glass-roughness.jpg",
    metalness: 0,
    roughness: 0.1,
    transmission: 0.98,
    ior: 1.52,
    defaultTint: "#ffffff",
  },
}

export const MATCAP_PRESETS = {
  kunzite: { id: "kunzite", name: "Kunzite", matcap: "/matcaps/kunzite.png" },
  pearl1: { id: "pearl1", name: "Pearl Iridescent", matcap: "/matcaps/pearl-1.png" },
  pearl2: { id: "pearl2", name: "Pearl Dark", matcap: "/matcaps/pearl-2.png" },
  pearl3: { id: "pearl3", name: "Pearl Soft", matcap: "/matcaps/pearl-3.png" },
  pearl4: { id: "pearl4", name: "Pearl Pink", matcap: "/matcaps/pearl-4.png" },
  negative: { id: "negative", name: "Negative", matcap: "/matcaps/negative.png" },
  metal: { id: "metal", name: "Metal Scratched", matcap: "/matcaps/metal.png" },
  metal2: { id: "metal2", name: "Metal Polished", matcap: "/matcaps/metal-2.png" },
  spiral: { id: "spiral", name: "Spiral Glass", matcap: "/matcaps/spiral.png" },
  skin: { id: "skin", name: "Skin Light", matcap: "/matcaps/skin.png" },
  skin2: { id: "skin2", name: "Skin Fair", matcap: "/matcaps/skin-2.png" },
  skin3: { id: "skin3", name: "Skin Medium", matcap: "/matcaps/skin-3.png" },
  skin4: { id: "skin4", name: "Skin Tan", matcap: "/matcaps/skin-4.png" },
  skin5: { id: "skin5", name: "Skin Deep", matcap: "/matcaps/skin-5.png" },
  softGold: { id: "softGold", name: "Soft Gold", matcap: "/matcaps/soft-gold.png" },
  zoisite: { id: "zoisite", name: "Zoisite Amber", matcap: "/matcaps/zoisite.png" },
  chrome1: { id: "chrome1", name: "Chrome Studio", matcap: "/matcaps/chrome-1.png" },
  chrome2: { id: "chrome2", name: "Chrome Clean", matcap: "/matcaps/chrome-2.png" },
  chrome3: { id: "chrome3", name: "Chrome Rainbow", matcap: "/matcaps/chrome-3.png" },
  chrome4: { id: "chrome4", name: "Chrome Iridescent", matcap: "/matcaps/chrome-4.png" },
  gold: { id: "gold", name: "Gold", matcap: "/matcaps/gold.png" },
  copper: { id: "copper", name: "Copper", matcap: "/matcaps/copper.png" },
  blood: { id: "blood", name: "Blood Red", matcap: "/matcaps/blood.png" },
  blueShine: { id: "blueShine", name: "Blue Shine", matcap: "/matcaps/blue-shine.png" },
  blueRefl: { id: "blueRefl", name: "Blue Metallic", matcap: "/matcaps/blue-refl.png" },
  cyberpunk: { id: "cyberpunk", name: "Cyberpunk", matcap: "/matcaps/cyberpunk.png" },
  nebula: { id: "nebula", name: "Nebula", matcap: "/matcaps/nebula.jpg" },
  oilBubble: { id: "oilBubble", name: "Oil Bubble", matcap: "/matcaps/oil-bubble.jpg" },
  steelHorizon: { id: "steelHorizon", name: "Steel Horizon", matcap: "/matcaps/steel-horizon.png" },
  forestGlow: { id: "forestGlow", name: "Forest Glow", matcap: "/matcaps/forest-glow.png" },
  skyEarth: { id: "skyEarth", name: "Sky Earth", matcap: "/matcaps/sky-earth.png" },
  sunsetTeal: { id: "sunsetTeal", name: "Sunset Teal", matcap: "/matcaps/sunset-teal.png" },
  terracottaGloss: { id: "terracottaGloss", name: "Terracotta Gloss", matcap: "/matcaps/terracotta-gloss.png" },
  obsidian: { id: "obsidian", name: "Obsidian", matcap: "/matcaps/obsidian.png" },
}

export type MaterialPreset = typeof MATERIAL_PRESETS[keyof typeof MATERIAL_PRESETS]
export type MatcapPreset = typeof MATCAP_PRESETS[keyof typeof MATCAP_PRESETS]
